# Generated by Django 4.0.2 on 2022-09-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authorbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorbankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
