# Generated by Django 4.0.2 on 2022-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='serial_number',
            field=models.IntegerField(default=1),
        ),
    ]
