# Generated by Django 4.0.2 on 2022-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0002_level_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
