# Generated by Django 4.0.2 on 2022-08-08 09:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0003_remove_level_serial_number_alter_level_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sales_copy',
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
    ]
