# Generated by Django 4.0.2 on 2022-08-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0005_alter_course_author_alter_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='e_learning.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.AddField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='e_learning.course'),
            preserve_default=False,
        ),
    ]
