# Generated by Django 4.0.2 on 2022-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0006_rerequisite_delete_prerequisite_learning_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='list_items',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rerequisite',
            name='list_items',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
