# Generated by Django 4.0.2 on 2022-08-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0008_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rerequisite',
            new_name='Prerequisite',
        ),
    ]
