# Generated by Django 4.0.2 on 2022-08-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0009_rename_rerequisite_prerequisite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
