# Generated by Django 4.0.2 on 2022-08-09 13:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0013_alter_course_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certifications',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.TextField(max_length=400),
        ),
    ]
