# Generated by Django 4.0.2 on 2022-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0014_alter_course_certifications_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.IntegerField(help_text='put in weeks example; 12 Weeks'),
        ),
    ]
