# Generated by Django 4.0.2 on 2022-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0015_alter_course_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.CharField(help_text='put in weeks example; 12 Weeks', max_length=200),
        ),
    ]
