# Generated by Django 4.0.2 on 2022-08-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_author_percentage_comm'),
        ('e_learning', '0018_alter_modulee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='percentage_commision',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='percent_commission', to='payment.authorcommision'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuthorCourse',
        ),
    ]
