# Generated by Django 4.0.2 on 2022-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0019_usercourse_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='commission',
            field=models.FloatField(),
        ),
    ]
