# Generated by Django 4.0.2 on 2022-08-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentexchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentexchangerate',
            options={'ordering': ['-created_at']},
        ),
    ]
