# Generated by Django 4.0.2 on 2022-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentexchangerate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentexchangerate',
            name='exchange_rate',
            field=models.IntegerField(),
        ),
    ]
