# Generated by Django 4.0.2 on 2022-08-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_author_percentage_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='author_percentage_comm',
        ),
    ]
