# Generated by Django 4.0.2 on 2022-08-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_handle', '0002_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhandle',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_handle.social'),
        ),
    ]
