# Generated by Django 4.0.2 on 2022-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_handle', '0004_email_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
