# Generated by Django 4.0.2 on 2022-08-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0002_alter_partners_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner'},
        ),
        migrations.AlterModelOptions(
            name='videoreview',
            options={'verbose_name': ''},
        ),
    ]
