# Generated by Django 4.0.2 on 2022-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0003_alter_partners_options_alter_videoreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoreview',
            options={},
        ),
        migrations.AddField(
            model_name='sitereview',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
