# Generated by Django 4.0.2 on 2022-08-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0004_alter_videoreview_options_sitereview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
