# Generated by Django 4.0.2 on 2022-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0005_alter_sitereview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/video_review'),
        ),
    ]
