# Generated by Django 4.0.2 on 2022-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0007_alter_videoreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='vidio_link',
            field=models.CharField(max_length=250),
        ),
    ]
