# Generated by Django 4.0.2 on 2022-08-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0008_alter_videoreview_vidio_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoreview',
            old_name='vidio_link',
            new_name='id_number',
        ),
    ]
