# Generated by Django 4.0.2 on 2022-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0010_sitereview_career_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='career_title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
