# Generated by Django 4.0.2 on 2022-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metafeatures', '0011_alter_sitereview_career_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
